language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t carlos116/react-dev -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true carlos116/react-dev npm test -- --coverage

after_success:
  - docker build -t carlos116/react-stable ./client
  - docker build -t carlos116/nginx-stable ./nginx
  - docker build -t carlos116/server-stable ./server
  - docker build -t carlos116/worker-stable ./worker